### PR TITLE
Update hook for enqueuing and registering assets

### PR DESCRIPTION
**Pull request by elliottpost**
ACF 5.9 changes the way the admin system works with ACF. In order for this JS & CSS to actually enqueue, the hooks need to change.

This pull request fixes issue #9 

It will apply the following changes :

* Change the CSS and JS hooks to use standard WP admin hooks for enqueuing CSS/JS since ACF hooks no longer cause these to output the CSS/JS.

### CODE REVIEW

**Comment by elliottpost** [comment]
@jameelmoses Here's the [_general_ documentation on 5.9](https://www.advancedcustomfields.com/blog/acf-5-9-exciting-new-features/ ). It discusses the admin refresh but it doesn't say anything about those filters. The actual [hook documentation](https://www.advancedcustomfields.com/resources/acf-input-admin_footer/) doesn't mention any changes.

Here's what I can tell you from this:

1. When I updated last night to ACF 5.9 RC-1 I noticed the modal stopped working for this plugin.
1. I added breakpoints to the plugin methods associated with these hooks. I confirmed each is firing still.
1. I inspected the source code for the page and found that none of the styles and JS were being enqueued in time as none were included with the rendered admin page source code.
1. This leads me to believe/hypothesize that during the admin revisions to ACF that they changed the order in which some of these hooks fire, and, while it was still registering/enqueuing the scripts, they would do so after the `admin_head` and `admin_footer` and as such the enqueued scripts/styles were enqueued too late.

Changing just the hooks associated for `wp_register_x` and `wp_enqueue_x`  seems sufficient here as we only need to ensure these JS and CSS files are being requested in the admin head/footer.

**Comment by jameelmoses** [comment]
@elliottpost got it. Yeah, I tried looking for a more detailed changelog / documentation too with no luck. My assumption is that this change would also be backwards compatible, right? Additionally, I think changing to the generic WP hooks will cause those files to be enqueued on every admin page and not necessarily only where ACF fields are rendered, although I think we can live with that. Thoughts?

**Comment by elliottpost** [comment]
@jameelmoses That's a really good point about it including on all pages and backwards compat. I haven't tested this on an older version of ACF but I imagine it would work fine. Perhaps we could check if it's on the edit screen before embedding. 

Maybe adding a conditional like:

```
$screen = get_current_screen();
if ( $screen->parent_base == 'edit' ) {
    wp_enqueue_x(...)
}
```

I could try this out and do some testing on it this weekend before merging into master.

**Comment by jameelmoses** [comment]
that'd be great if you have the time. thanks again for your work on this. i have several sites in active development right now using this with launch dates likely falling around the 5.9 release date, so this was on my radar but I hadn't had the time yet.

**Comment by jameelmoses** [comment]
also, i dont actually use this plugin anymore, but instead use https://github.com/jameelmoses/acf-flexible-content-extended, but i've been maintaining this version as well in case people don't want to edit their layouts in a modal too. figured i'd let you know in case you weren't aware of it.

**Comment by elliottpost** [comment]
Thanks, @jameelmoses! I didn't know about it. I'll check it out. I'll put a note on my calendar to try out the updates we mentioned above.

**Comment by elliottpost** [comment]
Sorry I forgot to follow-up on this. A bit overloaded with projects!

**Comment by jameelmoses** [comment]
No problem at all! Since 5.9 was officially dropped, I had to do it anyway. Thanks for the pr!

**Pull request merged**
